import { Course } from "@/types";

export const COURSES: Course[] = [
  // ── PYTHON ──────────────────────────────────────────────────────────────
  {
    id: "u-python-bootcamp",
    title: "100 Days of Code: The Complete Python Pro Bootcamp",
    platform: "udemy",
    url: "https://www.udemy.com/course/100-days-of-code/",
    instructor: "Dr. Angela Yu",
    rating: 4.7,
    reviews: 350000,
    price_inr: 499,
    duration_hours: 60,
    level: "beginner",
    topics: ["python", "programming", "coding", "beginner", "basics", "scripting"],
  },
  {
    id: "u-python-ds",
    title: "Python for Data Science and Machine Learning Bootcamp",
    platform: "udemy",
    url: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
    instructor: "Jose Portilla",
    rating: 4.6,
    reviews: 140000,
    price_inr: 499,
    duration_hours: 25,
    level: "beginner",
    topics: ["python", "data science", "machine learning", "pandas", "numpy", "matplotlib"],
  },
  {
    id: "td-python",
    title: "Python Programming Masterclass",
    platform: "tutedude",
    url: "https://tutedude.com/course/python-programming",
    instructor: "TuteDude Faculty",
    rating: 4.5,
    reviews: 12000,
    price_inr: 299,
    duration_hours: 30,
    level: "beginner",
    topics: ["python", "programming", "basics", "oop", "scripting"],
  },

  // ── DATA SCIENCE ────────────────────────────────────────────────────────
  {
    id: "u-ds-az",
    title: "Data Science A-Z™: Real-Life Data Science Exercises",
    platform: "udemy",
    url: "https://www.udemy.com/course/datascience/",
    instructor: "Kirill Eremenko",
    rating: 4.5,
    reviews: 85000,
    price_inr: 499,
    duration_hours: 21,
    level: "beginner",
    topics: ["data science", "statistics", "data analysis", "sql", "tableau"],
  },
  {
    id: "td-data-science",
    title: "Data Science & Analytics Full Course",
    platform: "tutedude",
    url: "https://tutedude.com/course/data-science",
    instructor: "TuteDude Faculty",
    rating: 4.6,
    reviews: 8000,
    price_inr: 399,
    duration_hours: 40,
    level: "beginner",
    topics: ["data science", "python", "pandas", "numpy", "visualization", "statistics"],
  },

  // ── MACHINE LEARNING ────────────────────────────────────────────────────
  {
    id: "u-ml-az",
    title: "Machine Learning A-Z: AI, Python & R + ChatGPT",
    platform: "udemy",
    url: "https://www.udemy.com/course/machinelearning/",
    instructor: "Kirill Eremenko & Hadelin de Ponteves",
    rating: 4.5,
    reviews: 200000,
    price_inr: 499,
    duration_hours: 44,
    level: "intermediate",
    topics: ["machine learning", "python", "regression", "classification", "clustering", "deep learning"],
  },
  {
    id: "u-ml-andrew",
    title: "Machine Learning Specialization",
    platform: "udemy",
    url: "https://www.udemy.com/course/machine-learning/",
    instructor: "Andrew Ng",
    rating: 4.9,
    reviews: 180000,
    price_inr: 499,
    duration_hours: 35,
    level: "beginner",
    topics: ["machine learning", "supervised learning", "neural networks", "algorithms", "mathematics"],
  },
  {
    id: "td-ml",
    title: "Machine Learning with Python",
    platform: "tutedude",
    url: "https://tutedude.com/course/machine-learning",
    instructor: "TuteDude Faculty",
    rating: 4.5,
    reviews: 5000,
    price_inr: 399,
    duration_hours: 35,
    level: "intermediate",
    topics: ["machine learning", "python", "scikit-learn", "algorithms", "model evaluation"],
  },

  // ── DEEP LEARNING / AI ──────────────────────────────────────────────────
  {
    id: "u-dl-az",
    title: "Deep Learning A-Z 2024: Neural Networks, AI & ChatGPT",
    platform: "udemy",
    url: "https://www.udemy.com/course/deeplearning/",
    instructor: "Kirill Eremenko & Hadelin de Ponteves",
    rating: 4.5,
    reviews: 130000,
    price_inr: 499,
    duration_hours: 23,
    level: "intermediate",
    topics: ["deep learning", "neural networks", "tensorflow", "keras", "cnn", "rnn", "nlp"],
  },
  {
    id: "u-pytorch",
    title: "PyTorch for Deep Learning & Machine Learning",
    platform: "udemy",
    url: "https://www.udemy.com/course/pytorch-for-deep-learning/",
    instructor: "Daniel Bourke",
    rating: 4.7,
    reviews: 55000,
    price_inr: 499,
    duration_hours: 44,
    level: "intermediate",
    topics: ["pytorch", "deep learning", "neural networks", "computer vision", "nlp"],
  },
  {
    id: "td-dl",
    title: "Deep Learning & AI Fundamentals",
    platform: "tutedude",
    url: "https://tutedude.com/course/deep-learning",
    instructor: "TuteDude Faculty",
    rating: 4.4,
    reviews: 3500,
    price_inr: 399,
    duration_hours: 30,
    level: "intermediate",
    topics: ["deep learning", "tensorflow", "neural networks", "ai", "image recognition"],
  },

  // ── WEB DEVELOPMENT ─────────────────────────────────────────────────────
  {
    id: "u-web-2024",
    title: "The Complete 2024 Web Development Bootcamp",
    platform: "udemy",
    url: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    instructor: "Dr. Angela Yu",
    rating: 4.7,
    reviews: 420000,
    price_inr: 499,
    duration_hours: 61,
    level: "beginner",
    topics: ["html", "css", "javascript", "react", "nodejs", "sql", "web development", "frontend", "backend"],
  },
  {
    id: "td-webdev",
    title: "Full Stack Web Development",
    platform: "tutedude",
    url: "https://tutedude.com/course/web-development",
    instructor: "TuteDude Faculty",
    rating: 4.5,
    reviews: 15000,
    price_inr: 299,
    duration_hours: 50,
    level: "beginner",
    topics: ["html", "css", "javascript", "react", "nodejs", "mongodb", "full stack", "web development"],
  },

  // ── JAVASCRIPT / REACT ──────────────────────────────────────────────────
  {
    id: "u-js-complete",
    title: "The Complete JavaScript Course 2024",
    platform: "udemy",
    url: "https://www.udemy.com/course/the-complete-javascript-course/",
    instructor: "Jonas Schmedtmann",
    rating: 4.7,
    reviews: 220000,
    price_inr: 499,
    duration_hours: 69,
    level: "beginner",
    topics: ["javascript", "es6", "dom", "oop", "async", "node", "frontend"],
  },
  {
    id: "u-react",
    title: "React - The Complete Guide 2024 (incl. Next.js)",
    platform: "udemy",
    url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
    instructor: "Maximilian Schwarzmüller",
    rating: 4.6,
    reviews: 210000,
    price_inr: 499,
    duration_hours: 68,
    level: "intermediate",
    topics: ["react", "nextjs", "hooks", "redux", "typescript", "frontend"],
  },
  {
    id: "td-react",
    title: "React JS Complete Course",
    platform: "tutedude",
    url: "https://tutedude.com/course/react-js",
    instructor: "TuteDude Faculty",
    rating: 4.5,
    reviews: 9000,
    price_inr: 299,
    duration_hours: 35,
    level: "intermediate",
    topics: ["react", "hooks", "redux", "context api", "frontend", "javascript"],
  },

  // ── SQL / DATABASES ─────────────────────────────────────────────────────
  {
    id: "u-sql",
    title: "The Complete SQL Bootcamp: Go from Zero to Hero",
    platform: "udemy",
    url: "https://www.udemy.com/course/the-complete-sql-bootcamp/",
    instructor: "Jose Portilla",
    rating: 4.7,
    reviews: 140000,
    price_inr: 499,
    duration_hours: 9,
    level: "beginner",
    topics: ["sql", "database", "postgresql", "queries", "joins", "data analysis"],
  },
  {
    id: "td-sql",
    title: "SQL & Database Management",
    platform: "tutedude",
    url: "https://tutedude.com/course/sql-database",
    instructor: "TuteDude Faculty",
    rating: 4.4,
    reviews: 6000,
    price_inr: 299,
    duration_hours: 20,
    level: "beginner",
    topics: ["sql", "mysql", "database", "queries", "normalization"],
  },

  // ── STATISTICS / MATH ───────────────────────────────────────────────────
  {
    id: "u-stats",
    title: "Statistics & Mathematics for Data Science & ML",
    platform: "udemy",
    url: "https://www.udemy.com/course/statistics-for-data-science-data-analytics/",
    instructor: "Ryan Ahmed",
    rating: 4.5,
    reviews: 35000,
    price_inr: 499,
    duration_hours: 16,
    level: "beginner",
    topics: ["statistics", "probability", "mathematics", "linear algebra", "calculus", "data science"],
  },

  // ── CLOUD / DEVOPS ──────────────────────────────────────────────────────
  {
    id: "u-aws",
    title: "AWS Certified Solutions Architect – Associate 2024",
    platform: "udemy",
    url: "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/",
    instructor: "Stephane Maarek",
    rating: 4.7,
    reviews: 220000,
    price_inr: 499,
    duration_hours: 27,
    level: "intermediate",
    topics: ["aws", "cloud", "devops", "infrastructure", "deployment", "s3", "ec2"],
  },
  {
    id: "td-cloud",
    title: "Cloud Computing & DevOps Fundamentals",
    platform: "tutedude",
    url: "https://tutedude.com/course/cloud-devops",
    instructor: "TuteDude Faculty",
    rating: 4.4,
    reviews: 4000,
    price_inr: 349,
    duration_hours: 30,
    level: "beginner",
    topics: ["cloud", "aws", "devops", "docker", "kubernetes", "deployment"],
  },

  // ── EXCEL / ANALYTICS TOOLS ─────────────────────────────────────────────
  {
    id: "u-excel",
    title: "Microsoft Excel - Excel from Beginner to Advanced",
    platform: "udemy",
    url: "https://www.udemy.com/course/microsoft-excel-2013-from-beginner-to-advanced-and-beyond/",
    instructor: "Kyle Pew",
    rating: 4.6,
    reviews: 540000,
    price_inr: 499,
    duration_hours: 19,
    level: "beginner",
    topics: ["excel", "spreadsheet", "data analysis", "formulas", "pivot tables", "visualization"],
  },

  // ── CLASS CENTRAL – PYTHON ───────────────────────────────────────────────
  {
    id: "cc-python-everybody",
    title: "Programming for Everybody (Getting Started with Python)",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/python-4319",
    instructor: "Dr. Chuck Severance · University of Michigan",
    rating: 4.8,
    reviews: 290000,
    price_inr: 0,
    duration_hours: 19,
    level: "beginner",
    topics: ["python", "programming", "basics", "beginner", "coding", "scripting"],
  },
  {
    id: "cc-python-google",
    title: "Crash Course on Python – Google",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/python-crash-course-18240",
    instructor: "Google Career Certificates",
    rating: 4.7,
    reviews: 120000,
    price_inr: 0,
    duration_hours: 32,
    level: "beginner",
    topics: ["python", "programming", "oop", "scripting", "automation", "basics"],
  },

  // ── CLASS CENTRAL – DATA SCIENCE ────────────────────────────────────────
  {
    id: "cc-ds-ibm",
    title: "What is Data Science? – IBM",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/what-is-datascience-26",
    instructor: "IBM Skills Network",
    rating: 4.7,
    reviews: 85000,
    price_inr: 0,
    duration_hours: 9,
    level: "beginner",
    topics: ["data science", "introduction", "statistics", "data analysis", "career"],
  },
  {
    id: "cc-ds-harvard",
    title: "Data Science: R Basics – Harvard",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/edx-data-science-r-basics-9253",
    instructor: "Rafael Irizarry · Harvard University",
    rating: 4.6,
    reviews: 42000,
    price_inr: 0,
    duration_hours: 40,
    level: "beginner",
    topics: ["data science", "r programming", "statistics", "data analysis", "visualization"],
  },

  // ── CLASS CENTRAL – MACHINE LEARNING ────────────────────────────────────
  {
    id: "cc-ml-stanford",
    title: "Machine Learning – Stanford University",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/machine-learning-835",
    instructor: "Andrew Ng · Stanford University",
    rating: 4.9,
    reviews: 250000,
    price_inr: 0,
    duration_hours: 55,
    level: "intermediate",
    topics: ["machine learning", "supervised learning", "neural networks", "algorithms", "mathematics", "regression", "classification"],
  },
  {
    id: "cc-ml-specialization",
    title: "Machine Learning Specialization – DeepLearning.AI",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/machine-learning-andrew-ng-106584",
    instructor: "Andrew Ng · DeepLearning.AI",
    rating: 4.9,
    reviews: 180000,
    price_inr: 0,
    duration_hours: 96,
    level: "beginner",
    topics: ["machine learning", "supervised learning", "unsupervised learning", "neural networks", "python", "algorithms"],
  },

  // ── CLASS CENTRAL – DEEP LEARNING / AI ──────────────────────────────────
  {
    id: "cc-dl-deeplearningai",
    title: "Deep Learning Specialization – DeepLearning.AI",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/neural-networks-deep-learning-9058",
    instructor: "Andrew Ng · DeepLearning.AI",
    rating: 4.9,
    reviews: 160000,
    price_inr: 0,
    duration_hours: 80,
    level: "intermediate",
    topics: ["deep learning", "neural networks", "cnn", "rnn", "tensorflow", "ai", "nlp"],
  },
  {
    id: "cc-ai-mit",
    title: "Introduction to Deep Learning – MIT",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/mit-introduction-deep-learning-53150",
    instructor: "Alexander Amini · MIT",
    rating: 4.8,
    reviews: 55000,
    price_inr: 0,
    duration_hours: 20,
    level: "intermediate",
    topics: ["deep learning", "neural networks", "tensorflow", "pytorch", "ai", "computer vision"],
  },

  // ── CLASS CENTRAL – WEB DEVELOPMENT ────────────────────────────────────
  {
    id: "cc-web-html-meta",
    title: "Introduction to Front-End Development – Meta",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/introduction-to-front-end-development-103029",
    instructor: "Meta Staff · Meta",
    rating: 4.7,
    reviews: 65000,
    price_inr: 0,
    duration_hours: 28,
    level: "beginner",
    topics: ["html", "css", "javascript", "frontend", "web development", "react", "ui"],
  },
  {
    id: "cc-fullstack-meta",
    title: "Meta Back-End Developer Professional Certificate",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/meta-back-end-developer-106734",
    instructor: "Meta Staff · Meta",
    rating: 4.7,
    reviews: 38000,
    price_inr: 0,
    duration_hours: 240,
    level: "intermediate",
    topics: ["backend", "python", "django", "sql", "api", "full stack", "web development", "nodejs"],
  },

  // ── CLASS CENTRAL – SQL / DATABASES ─────────────────────────────────────
  {
    id: "cc-sql-stanford",
    title: "Databases: Relational Databases and SQL – Stanford",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/edx-databases-5-sql-12255",
    instructor: "Jennifer Widom · Stanford University",
    rating: 4.8,
    reviews: 28000,
    price_inr: 0,
    duration_hours: 15,
    level: "beginner",
    topics: ["sql", "database", "relational database", "queries", "joins", "postgresql"],
  },

  // ── CLASS CENTRAL – STATISTICS / MATH ───────────────────────────────────
  {
    id: "cc-stats-duke",
    title: "Introduction to Probability and Data – Duke University",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/probability-intro-9609",
    instructor: "Mine Çetinkaya-Rundel · Duke University",
    rating: 4.7,
    reviews: 40000,
    price_inr: 0,
    duration_hours: 20,
    level: "beginner",
    topics: ["statistics", "probability", "data analysis", "mathematics", "data science"],
  },
  {
    id: "cc-linear-algebra-mit",
    title: "Linear Algebra – MIT OpenCourseWare",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/independent-linear-algebra-18697",
    instructor: "Gilbert Strang · MIT",
    rating: 4.9,
    reviews: 25000,
    price_inr: 0,
    duration_hours: 35,
    level: "intermediate",
    topics: ["linear algebra", "mathematics", "machine learning", "calculus", "statistics"],
  },

  // ── CLASS CENTRAL – CLOUD / DEVOPS ──────────────────────────────────────
  {
    id: "cc-cloud-google",
    title: "Google Cloud Fundamentals: Core Infrastructure",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/gcp-fundamentals-7244",
    instructor: "Google Cloud Training",
    rating: 4.6,
    reviews: 32000,
    price_inr: 0,
    duration_hours: 12,
    level: "beginner",
    topics: ["cloud", "gcp", "google cloud", "devops", "infrastructure", "deployment"],
  },
  {
    id: "cc-devops-ibm",
    title: "Introduction to DevOps – IBM",
    platform: "classcentral",
    url: "https://www.classcentral.com/course/intro-to-devops-18658",
    instructor: "IBM Skills Network",
    rating: 4.6,
    reviews: 22000,
    price_inr: 0,
    duration_hours: 12,
    level: "beginner",
    topics: ["devops", "cloud", "docker", "kubernetes", "ci/cd", "deployment", "aws"],
  },
];

function scoreMatch(course: Course, topics: string[]): number {
  const queryTopics = topics.map((t) => t.toLowerCase());
  let score = 0;
  for (const qt of queryTopics) {
    for (const ct of course.topics) {
      if (ct.includes(qt) || qt.includes(ct)) score += 1;
    }
  }
  return score;
}

export function matchCourses(topics: string[], level: string, limit = 3): Course[] {
  const levelMap: Record<string, number> = { beginner: 0, intermediate: 1, advanced: 2 };
  const userLevel = levelMap[level] ?? 0;

  return COURSES.filter((c) => {
    const courseLevel = levelMap[c.level] ?? 0;
    return courseLevel <= userLevel + 1;
  })
    .map((c) => ({ course: c, score: scoreMatch(c, topics) }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || b.course.rating - a.course.rating)
    .slice(0, limit)
    .map((x) => x.course);
}
